// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Block from "bs-platform/lib/es6/block.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as UserPng from "../img/user.png";

var logo = UserPng.default;

var bouton = {
  backgroundColor: "white",
  border: "none",
  clear: "right",
  color: "#799dec",
  float: "right",
  fontSize: "18px",
  fontWeight: "bold",
  textDecoration: "none",
  textShadow: "0px 4px 2px rgba(0, 0, 0, 0.32), 0px 1px 0px #6182ca, 0px 2px 0px #4f6aa7, 0px 3px 0px #5470ad"
};

var image = {
  height: "1px",
  visibility: "hidden",
  width: "1px"
};

var title = {
  fontSize: "xxx-large",
  textAlign: "center"
};

var component = ReasonReact.statelessComponent("Form");

var card = {
  border: "2px solid #898989",
  clear: "right",
  float: "right",
  padding: "1rem",
  borderRadius: "4px"
};

var Styles = {
  card: card
};

function make(ctx, appSend, _children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("form", {
                          onSubmit: (function (ev) {
                              ev.preventDefault();
                              Curry._1(appSend, /* UpdateInput */Block.__(0, [
                                      ctx[/* input */0],
                                      ctx[/* utilisateur */1]
                                    ]));
                              return Curry._1(appSend, /* Search */1);
                            })
                        }, React.createElement("h1", {
                              style: title
                            }, "Forum " + ctx[/* input */0]), React.createElement("button", {
                              style: bouton,
                              type: "submit"
                            }, "Refresh"), React.createElement("img", {
                              style: image,
                              alt: "",
                              src: logo,
                              onLoad: (function (ev) {
                                  Curry._1(appSend, /* UpdateInput */Block.__(0, [
                                          ctx[/* input */0],
                                          ctx[/* utilisateur */1]
                                        ]));
                                  return Curry._1(appSend, /* Search */1);
                                })
                            }));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

export {
  logo ,
  bouton ,
  image ,
  title ,
  component ,
  Styles ,
  make ,
  
}
/* logo Not a pure module */
